services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: research-backend
    tty: true
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    network_mode: host
    volumes:
      - type: bind
        source: ./backend
        target: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: research-frontend
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app

  # database:
  #   image: chromadb/chroma:latest
  #   container_name: research-database
  #   ports:
  #     - "8001:8000"

  # bot:
  #   build:
  #     context: ./telegram_bot
  #     dockerfile: Dockerfile
  #   container_name: telegram-bot
  #   command: python main.py
  #   environment:
  #     TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  #   volumes:
  #     - type: bind
  #       source: ./telegram_bot
  #       target: /app
  #   network_mode: host

